#!/usr/bin/env python3

# Copyright 2026 Unicorn Operations Ltd.
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial.
# Please see LICENSE files in the repository root for full details.

"""
Keeps the Element name out of the translations people can reach in Family Chat (unicornops/familychat-android#9).

The English strings were rebranded in place, but the upstream translations (values-*/translations.xml) still say
"Element" or "Element X" in a few places. Editing those files would conflict on every upstream string sync, so this
script writes per-locale overrides into the app module instead (app/src/main/res/values-*/familychat_brand.xml):
app resources win over library resources for the same qualifier.

    tools/familychat/brand_translations.py          # regenerate the override files
    tools/familychat/brand_translations.py --check  # CI: fail if they are stale or a new string names Element

Run it after merging an upstream release. If --check reports a new key, add it to PATCHED or FIXED (reachable in
Family Chat), or to KEPT with the reason.
"""

import argparse
import glob
import html
import os
import re
import sys

BRAND = "Family Chat"
OUTPUT_DIR = "app/src/main/res"
OUTPUT_NAME = "familychat_brand.xml"

# Reachable strings: every "Element X" / "Element" in the translation becomes the brand name.
PATCHED = {
    "screen_room_timeline_legacy_call",  # timeline item for an unsupported call
    "screen_notification_settings_sound_element_default",  # notification sound picker
    "screen_notification_settings_sound_element_fade",
}

# Reachable strings replaced in every locale, English included, by a fixed value.
FIXED = {
    # First screen of the app. "Be in your element" is a pun on Element's name; the brand name needs no translation.
    "screen_onboarding_welcome_title": BRAND,
}

# Strings that name Element and stay as they are: deliberate, or not reachable in Family Chat.
KEPT = {
    # AGPL attribution on the About screen: naming Element is the point.
    "screen_about_source_code_description": "upstream attribution",
    # Element Call: kept or removed with the decision in unicornops/family-chat#258.
    "screen_incoming_call_subtitle_android": "Element Call, unicornops/family-chat#258",
    "call_invalid_audio_device_bluetooth_devices_disabled": "Element Call, unicornops/family-chat#258",
    # Developer settings (behind developer mode), and also Element Call.
    "screen_advanced_settings_element_call_base_url": "developer settings, unicornops/family-chat#258",
    "screen_advanced_settings_element_call_base_url_description": "developer settings, unicornops/family-chat#258",
    # The account provider is locked to safechat.family, so element.io is never offered.
    "screen_server_confirmation_message_login_element_dot_io": "account provider locked to safechat.family",
    # isElementProEnforced() is false in this fork.
    "screen_change_server_error_element_pro_required_title": "Element Pro check disabled",
    "screen_change_server_error_element_pro_required_message": "Element Pro check disabled",
    # Only shown when the Element Classic app is installed with a session to import.
    "screen_missing_key_backup_open_element_classic": "Element Classic import",
    "screen_missing_key_backup_step_1": "Element Classic import",
    # "Element" is the ordinary word for "item" in some languages here.
    "screen_media_upload_preview_item_count": "ordinary word, not the brand",
}

# "Element" not followed by a lower-case letter: catches "Element", "Element X", "Element에서", not "Elemente".
ELEMENT = re.compile(r"Element(?![a-zà-öø-ÿ])")
ELEMENT_X = re.compile(r"Element[  ]X")
STRING = re.compile(r'^\s*<string name="(?P<name>[^"]+)"(?P<attrs>[^>]*)>(?P<value>.*)</string>\s*$')

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
  ~ Copyright 2026 Unicorn Operations Ltd.
  ~
  ~ SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial.
  ~ Please see LICENSE files in the repository root for full details.
  -->
<!-- Generated by tools/familychat/brand_translations.py, do not edit. Used by the library modules. -->
<resources xmlns:tools="http://schemas.android.com/tools" tools:ignore="UnusedResources">
"""


def read_translations():
    """Returns {qualifier: {name: raw value}} for every library string resource outside the app module."""
    result = {}
    for path in sorted(glob.glob("**/src/main/res/values*/*.xml", recursive=True)):
        if "/build/" in path or path.startswith(OUTPUT_DIR + "/"):
            continue
        qualifier = path.split("/res/")[1].split("/")[0]
        with open(path, encoding="utf-8") as f:
            for line in f:
                match = STRING.match(line)
                if match:
                    result.setdefault(qualifier, {})[match["name"]] = match["value"]
    return result


def patch(value):
    return ELEMENT.sub(BRAND, ELEMENT_X.sub(BRAND, value))


def build_overrides(translations):
    """Returns ({qualifier: {name: value}}, [unknown "qualifier name" entries])."""
    overrides = {}
    unknown = []
    defaults = translations.get("values", {})
    for qualifier, strings in translations.items():
        for name, value in strings.items():
            if name in FIXED:
                overrides.setdefault(qualifier, {})[name] = html.escape(FIXED[name], quote=False)
            elif name in PATCHED:
                if ELEMENT.search(value):
                    overrides.setdefault(qualifier, {})[name] = patch(value)
            elif ELEMENT.search(value) and name not in KEPT:
                unknown.append(f"{qualifier} {name}: {value}")
    # Lint (ExtraTranslation) wants every key overridden in a locale to exist in the app's default locale too.
    default_overrides = overrides.setdefault("values", {})
    for qualifier, strings in list(overrides.items()):
        for name in strings:
            default_overrides.setdefault(name, defaults[name])
    return overrides, unknown


def render(strings):
    lines = [f'    <string name="{name}">{value}</string>\n' for name, value in sorted(strings.items())]
    return HEADER + "".join(lines) + "</resources>\n"


def expected_files(overrides):
    return {
        os.path.join(OUTPUT_DIR, qualifier, OUTPUT_NAME): render(strings)
        for qualifier, strings in overrides.items()
    }


def existing_files():
    return set(glob.glob(os.path.join(OUTPUT_DIR, "values*", OUTPUT_NAME)))


def main():
    parser = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail instead of writing when files are stale")
    args = parser.parse_args()

    overrides, unknown = build_overrides(read_translations())
    expected = expected_files(overrides)
    failed = False

    if unknown:
        failed = True
        print("Strings that name Element and are not classified in tools/familychat/brand_translations.py:", file=sys.stderr)
        for entry in sorted(unknown):
            print(f"  {entry}", file=sys.stderr)

    stale = sorted(path for path, content in expected.items()
                   if not os.path.exists(path) or open(path, encoding="utf-8").read() != content)
    extra = sorted(existing_files() - set(expected))

    if args.check:
        if stale or extra:
            failed = True
            print("Override files are out of date; run tools/familychat/brand_translations.py:", file=sys.stderr)
            for path in stale + extra:
                print(f"  {path}", file=sys.stderr)
    else:
        for path in stale:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                f.write(expected[path])
        for path in extra:
            os.remove(path)
        print(f"{len(expected)} override file(s): {len(stale)} written, {len(extra)} removed.")

    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
