#!/usr/bin/env python3

# Copyright 2026 Unicorn Operations Ltd.
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial.
# Please see LICENSE files in the repository root for full details.

"""
Keeps the Element name out of the translations people can reach in Family Chat (unicornops/familychat-android#9).

The English strings were rebranded in place, but the upstream translations (values-*/translations.xml) still say
"Element" or "Element X" in a few places. Editing those files would conflict on every upstream string sync, so this
script writes per-locale overrides into the app module instead (app/src/main/res/values-*/familychat_brand.xml):
app resources win over library resources for the same qualifier.

    tools/familychat/brand_translations.py          # regenerate the override files
    tools/familychat/brand_translations.py --check  # CI: fail if they are stale or a new string names Element

Run it after merging an upstream release. If --check reports a new key, add it to PATCHED or FIXED (reachable in
Family Chat), or to KEPT with the reason.
"""

import argparse
import glob
import html
import os
import re
import sys
import xml.etree.ElementTree as ET

BRAND = "Family Chat"
OUTPUT_DIR = "app/src/main/res"
OUTPUT_NAME = "familychat_brand.xml"

# Reachable strings: every "Element X" / "Element" in the translation becomes the brand name.
PATCHED = {
    "screen_room_timeline_legacy_call",  # timeline item for an unsupported call
    "screen_notification_settings_sound_element_default",  # notification sound picker
    "screen_notification_settings_sound_element_fade",
}

# Reachable strings replaced in every locale, English included, by a fixed value.
FIXED = {
    # First screen of the app. "Be in your element" is a pun on Element's name; the brand name needs no translation.
    "screen_onboarding_welcome_title": BRAND,
}

# Strings that name Element and stay as they are: deliberate, or not reachable in Family Chat.
KEPT = {
    # AGPL attribution on the About screen: naming Element is the point.
    "screen_about_source_code_description": "upstream attribution",
    # Element Call: kept or removed with the decision in unicornops/family-chat#258.
    "screen_incoming_call_subtitle_android": "Element Call, unicornops/family-chat#258",
    "call_invalid_audio_device_bluetooth_devices_disabled": "Element Call, unicornops/family-chat#258",
    # Developer settings (behind developer mode), and also Element Call.
    "screen_advanced_settings_element_call_base_url": "developer settings, unicornops/family-chat#258",
    "screen_advanced_settings_element_call_base_url_description": "developer settings, unicornops/family-chat#258",
    # The account provider is locked to safechat.family, so element.io is never offered.
    "screen_server_confirmation_message_login_element_dot_io": "account provider locked to safechat.family",
    # isElementProEnforced() is false in this fork.
    "screen_change_server_error_element_pro_required_title": "Element Pro check disabled",
    "screen_change_server_error_element_pro_required_message": "Element Pro check disabled",
    # Only shown when the Element Classic app is installed with a session to import.
    "screen_missing_key_backup_open_element_classic": "Element Classic import",
    "screen_missing_key_backup_step_1": "Element Classic import",
    # Label of the call activity in the manifest, not translatable.
    "element_call": "Element Call, unicornops/family-chat#258",
    # "Element" is the ordinary word for "item" in some languages here.
    "screen_media_upload_preview_item_count": "ordinary word, not the brand",
}

# The brand as a whole word in any script: "Element", "Element X", "Element," but not "Elemente" or "Elementin".
ELEMENT = re.compile(r"Element(?!\w)")
ELEMENT_X = re.compile(r"Element[ \u00a0]X")
# Any form of the word, inflected or lower case ("Elementin", "elementa"): a PATCHED value still matching after the
# patch falls back to the English override rather than half-naming Element.
ANY_ELEMENT = re.compile(r"element", re.IGNORECASE)
# Single-line string with its raw (escaped) value, attributes in any order. Only used to copy values verbatim.
STRING = re.compile(r'^\s*<string\b(?P<attrs>[^>]*)>(?P<value>.*)</string>\s*$')
NAME = re.compile(r'\bname="(?P<name>[^"]+)"')

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
  ~ Copyright 2026 Unicorn Operations Ltd.
  ~
  ~ SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial.
  ~ Please see LICENSE files in the repository root for full details.
  -->
<!-- Generated by tools/familychat/brand_translations.py, do not edit. Used by the library modules. -->
<resources xmlns:tools="http://schemas.android.com/tools" tools:ignore="UnusedResources">
"""


def resource_files():
    for path in sorted(glob.glob("**/src/main/res/values*/*.xml", recursive=True)):
        if "/build/" in path or path.startswith(OUTPUT_DIR + "/"):
            continue
        yield path.split("/res/")[1].split("/")[0], path


def read_translations():
    """
    Returns ({qualifier: {name: raw value}}, {qualifier: {name: text}}).

    The raw values come from single-line <string> elements and are copied verbatim into the overrides. The texts come
    from a real XML parse of every <string>, <plurals> item and <string-array> item, and are what the Element check
    looks at, so multi-line strings and plurals cannot slip past it.
    """
    raw = {}
    texts = {}
    for qualifier, path in resource_files():
        with open(path, encoding="utf-8") as f:
            for line in f:
                match = STRING.match(line)
                name = match and NAME.search(match["attrs"])
                if name:
                    raw.setdefault(qualifier, {})[name["name"]] = match["value"]
        try:
            root = ET.parse(path).getroot()
        except ET.ParseError:
            continue
        for element in root:
            name = element.get("name")
            if element.tag == "string" and name:
                texts.setdefault(qualifier, {})[name] = "".join(element.itertext())
            elif element.tag in ("plurals", "string-array") and name:
                for index, item in enumerate(element.iter("item")):
                    texts.setdefault(qualifier, {})[f"{name}[{index}]"] = "".join(item.itertext())
    return raw, texts


def patch(value):
    return ELEMENT.sub(BRAND, ELEMENT_X.sub(BRAND, value))


def build_overrides(raw, texts):
    """Returns ({qualifier: {name: value}}, [problems])."""
    overrides = {}
    problems = []
    defaults = raw.get("values", {})
    for qualifier, strings in texts.items():
        for name, text in strings.items():
            key = name.split("[")[0]
            if key in FIXED:
                overrides.setdefault(qualifier, {})[key] = html.escape(FIXED[key], quote=False)
            elif key in PATCHED:
                if not ANY_ELEMENT.search(text):
                    continue
                value = raw.get(qualifier, {}).get(key)
                if value is None:
                    problems.append(f"{qualifier} {name}: not a single-line <string>, cannot override it")
                    continue
                patched = patch(value)
                if ANY_ELEMENT.search(patched):
                    # An inflected form ("Elementin oletus"): show the English default rather than guess the grammar.
                    patched = patch(defaults[key])
                overrides.setdefault(qualifier, {})[key] = patched
            elif ELEMENT.search(text) and key not in KEPT:
                problems.append(f"{qualifier} {name}: {text}")
    # Lint (ExtraTranslation) wants every key overridden in a locale to exist in the app's default locale too.
    default_overrides = overrides.setdefault("values", {})
    for qualifier, strings in list(overrides.items()):
        for name in strings:
            default_overrides.setdefault(name, patch(defaults[name]))
    return overrides, problems


def render(strings):
    lines = [f'    <string name="{name}">{value}</string>\n' for name, value in sorted(strings.items())]
    return HEADER + "".join(lines) + "</resources>\n"


def expected_files(overrides):
    return {
        os.path.join(OUTPUT_DIR, qualifier, OUTPUT_NAME): render(strings)
        for qualifier, strings in overrides.items()
    }


def existing_files():
    return set(glob.glob(os.path.join(OUTPUT_DIR, "values*", OUTPUT_NAME)))


def main():
    parser = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail instead of writing when files are stale")
    args = parser.parse_args()

    overrides, unknown = build_overrides(*read_translations())
    expected = expected_files(overrides)
    failed = False

    if unknown:
        failed = True
        print("Strings that name Element and are not handled by tools/familychat/brand_translations.py:", file=sys.stderr)
        for entry in sorted(unknown):
            print(f"  {entry}", file=sys.stderr)

    stale = sorted(path for path, content in expected.items()
                   if not os.path.exists(path) or open(path, encoding="utf-8").read() != content)
    extra = sorted(existing_files() - set(expected))

    if args.check:
        if stale or extra:
            failed = True
            print("Override files are out of date; run tools/familychat/brand_translations.py:", file=sys.stderr)
            for path in stale + extra:
                print(f"  {path}", file=sys.stderr)
    else:
        for path in stale:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                f.write(expected[path])
        for path in extra:
            os.remove(path)
        print(f"{len(expected)} override file(s): {len(stale)} written, {len(extra)} removed.")

    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
